### PR TITLE
Add Styled-Components, React-Apollo, Lodash

### PR DESCRIPTION
**Pull request by couturecraigj**
I thought that it might be nice to add some of these larger libraries on to your list.

### CODE REVIEW

**Comment by couturecraigj** [comment]
I went and added many of the modules that you listed as wanting added in #6.

**Comment by mastilver** [comment]
Thank you. Can you use `[version]` in the url?

The test is failing because we are using too much memory during the tests... I need to find a solution for that...

**Comment by couturecraigj** [comment]
Is this the method you want to use going forward.  I can definitely do that.  Can you should be the example that you are talking about?

**Comment by mastilver** [comment]
for example do `https://unpkg.com/react-apollo@[version]/react-apollo.browser.umd.js`

**Comment by couturecraigj** [comment]
I have been trying to make it work.  I am going to drop it.

**Comment by mastilver** [comment]
I'm closing this one, as there is too many modules that are not umd

**Pull request closed without merging**
